version: '3.9'

services:
  sgclickhouse:
    image: yandex/clickhouse-server:20.6.8.5
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./sg-clickhouse-data:/var/lib/clickhouse:z
      - ./docker:/docker-entrypoint-initdb.d:z,ro